### ISSUE TITLE
Trying to install nextcloud client on a Raspberry...

### ISSUE THREAD

**Issue by krrkrr** [istandthon7/desktop#1]
Hello.

I’m on a RPI 3, with Raspbian updated.

I followed the scripts… Installed qt5-qtwebengine-arm-bin… downloaded the client on istandthon7 client github…

When I launch ./init.sh, I got a reply saying the stable versions of libqt5keychain1/stable libminizip1/stable can’t be found.

When I launch ./nextcloud.sh: ./bin/nextcloud: error while loading shared libraries: libqt5keychain.so.1: cannot open shared object file: No such file or directory

What can I do ???

**Comment by istandthon7** [comment]
Hi~
My rpi info.
`$ cat /etc/*-release`
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

And apt source list
`$ cat /etc/apt/sources.list`
> deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi

I want you rpi info.
thanks~

**Comment by krrkrr** [comment]
Hi

Rpi info:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch

Apt source list:
deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi


Regards

**Comment by istandthon7** [comment]
Hi.
Thanks for comment.
I was fixed init.sh file.
You can download tar file at https://github.com/istandthon7/desktop/releases 
Or 
 `$ sudo apt install libqt5keychain1 libminizip1 libqt5quickwidgets5`
 `$ ./nextcloud.sh`
